name: Github Action Build PKGBUILD
on: push
jobs:
  build_for_arch:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-cacule-uksm-cjktty for arch
        uses: antman666/build-aur-action@mine
        with:
          repo-name: linux-xanmod-cacule-uksm-cjktty
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          tag: "linux-5.13.8-xanmod-uksm-cjktty-1_for_arch"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
