name: Github Action Build PKGBUILD
on: 
  push:
  workflow_dispatch:
jobs:
  build_for_arch:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-xanmod-tt-uksm-cjktty for arch
        uses: antman666/build-aur-action@mine
        with:
          repo-name: linux-xanmod-tt-uksm-cjktty
      - uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          tag: "linux-xanmod-tt-uksm-cjktty_v6.1.8-1"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
